[package]
name = "demoparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bitreader = "0.3.6"
protobuf = "3.1.0"

[dependencies.csgoproto]
path = "./csgoproto"

[profile.dev]
overflow-checks = false